name: testing
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  bloc: ^9.0.1
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.3
  freezed_annotation: ^3.1.0
  geolocator: ^14.0.2
  get_it: ^9.2.0
  google_fonts: ^6.3.3
  injectable: ^2.7.1+2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logger: ^2.6.2
  provider: ^6.1.5+1
  retrofit: ^4.9.1
  smooth_page_indicator: ^2.0.1

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.7.1
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  injectable_generator: ^2.8.1
  json_serializable: ^6.11.2
  mocktail: ^1.0.4
  retrofit_generator: ^10.2.0
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
